### ISSUE TITLE
Wrong version installed via npm?

### ISSUE THREAD

**Issue by Five-Cents** [GluuFederation/oxd-node#5]
npm version: 6.9.0
node verison: v10.12.2

Noticed an odd error when trying to use the introspect_access_token function:

```
TypeError: oxd.introspect_access_token is not a function
    at app.get (/var/www/ndr_gui/client.js:137:7)
    at Layer.handle [as handle_request] (/var/www/ndr_gui/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/ndr_gui/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/var/www/ndr_gui/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/www/ndr_gui/node_modules/express/lib/router/layer.js:95:5)
    at /var/www/ndr_gui/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/var/www/ndr_gui/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ndr_gui/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/var/www/ndr_gui/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/var/www/ndr_gui/node_modules/express/lib/router/layer.js:95:5)

```

I checked in on node_modules/oxd-node/index.js and there were no introspection functions.

I tried reinstalling today, but it seems that `npm i oxd-node` is pulling the wrong version.

**Comment by Five-Cents** [comment]
Downloaded the library and tried out using the introspection function, got the following error:

`2019-04-15 15:01:54,708 ERROR [org.xdi.oxd.server.Processor] org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "key_from_script" (Class org.xdi.oxd.server.introspection.BackCompatibleIntrospectionResponse), not marked as ignorable
 at [Source: org.jboss.resteasy.client.core.BaseClientResponse$InputStreamWrapper@3656feff; line: 1, column: 468] (through reference chain: org.xdi.oxd.server.introspection.BackCompatibleIntrospectionResponse["key_from_script"])
org.jboss.resteasy.spi.ReaderException: org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "key_from_script" (Class org.xdi.oxd.server.introspection.BackCompatibleIntrospectionResponse), not marked as ignorable
 at [Source: org.jboss.resteasy.client.core.BaseClientResponse$InputStreamWrapper@3656feff; line: 1, column: 468] (through reference chain: org.xdi.oxd.server.introspection.BackCompatibleIntrospectionResponse["key_from_script"])
        at org.jboss.resteasy.client.core.BaseClientResponse.readFrom(BaseClientResponse.java:477)
        at org.jboss.resteasy.client.core.BaseClientResponse.getEntity(BaseClientResponse.java:390)
        at org.jboss.resteasy.client.core.BaseClientResponse.getEntity(BaseClientResponse.java:361)
        at org.jboss.resteasy.client.core.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:64)
        at org.jboss.resteasy.client.core.ClientInvoker.invoke(ClientInvoker.java:128)
        at org.jboss.resteasy.client.core.ClientProxy.invoke(ClientProxy.java:89)
        at com.sun.proxy.$Proxy35.introspectToken(Unknown Source)
        at org.xdi.oxd.server.service.IntrospectionService.introspectToken(IntrospectionService.java:62)
        at org.xdi.oxd.server.service.IntrospectionService.introspectToken(IntrospectionService.java:36)
        at org.xdi.oxd.server.op.IntrospectAccessTokenOperation.execute(IntrospectAccessTokenOperation.java:35)
        at org.xdi.oxd.server.op.IntrospectAccessTokenOperation.execute(IntrospectAccessTokenOperation.java:16)
        at org.xdi.oxd.server.Processor.process(Processor.java:74)
        at org.xdi.oxd.server.Processor.process(Processor.java:49)
        at org.xdi.oxd.server.SocketProcessor.run(SocketProcessor.java:55)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "key_from_script" (Class org.xdi.oxd.server.introspection.BackCompatibleIntrospectionResponse), not marked as ignorable
 at [Source: org.jboss.resteasy.client.core.BaseClientResponse$InputStreamWrapper@3656feff; line: 1, column: 468] (through reference chain: org.xdi.oxd.server.introspection.BackCompatibleIntrospectionResponse["key_from_script"])
        at org.codehaus.jackson.map.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:53)
        at org.codehaus.jackson.map.deser.StdDeserializationContext.unknownFieldException(StdDeserializationContext.java:267)
        at org.codehaus.jackson.map.deser.std.StdDeserializer.reportUnknownProperty(StdDeserializer.java:673)
        at org.codehaus.jackson.map.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:659)
        at org.codehaus.jackson.map.deser.BeanDeserializer.handleUnknownProperty(BeanDeserializer.java:1365)
        at org.codehaus.jackson.map.deser.BeanDeserializer._handleUnknown(BeanDeserializer.java:725)
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:703)
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580)
        at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2704)
        at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1315)
        at org.codehaus.jackson.jaxrs.JacksonJsonProvider.readFrom(JacksonJsonProvider.java:419)
        at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:66)
        at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:56)
        at org.jboss.resteasy.client.core.BaseClientResponse.readFrom(BaseClientResponse.java:442)
        ... 16 more
2019-04-15 15:01:54,709 TRACE [org.xdi.oxd.server.Processor] Send back response: {"status":"error","data":{"error":"internal_error","details":null,"error_description":"Unknown internal server error occurs."}}
2019-04-15 15:01:54,709 ERROR [org.xdi.oxd.server.SocketProcessor] Quit. Enable to process command.`

Unsure if it's related to: https://github.com/GluuFederation/oxAuth/issues/1006

**Comment by nynymike** [comment]
In oxd version 4, we have swaggerized the oxd API, and recommend generating your own client.

**Comment by ldeveloperl1985** [comment]
@Five-Cents 
For `Unrecognized field "key_from_script"` issue you need turn off introspection interceptions scripts in your op configuration.
Configuration > Manage Custom Script > Introspection.

We solved this problem in OXD 4.0 which is still in developement process. here is instructions for OXD 4.0 https://github.com/GluuFederation/oxd/wiki/oxd-4.0.beta. you need generate your own client using swagger.

About npm version, it is not updated to npm repo. we will update it.

**Comment by ldeveloperl1985** [comment]
@Five-Cents library is now updated to npm

**Comment by Five-Cents** [comment]
@nynymike @ldeveloperl1985  thanks I'll look into generating my own client with OXD 4.0 instead. 

I'll close the ticket.
